# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.format]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.format-check]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--check",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.check-external-types]
description = "Run cargo check-external-types"
workspace = false
# cargo check-external-types needs a specific nightly toolchain,
# see https://github.com/awslabs/cargo-check-external-types#how-to-use
toolchain = "${TOOLCHAIN:nightly-2026-03-20}"
command = "cargo"
install_crate = false
args = ["check-external-types", "--all-features"]
