name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MSRV: "1.91"

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
      - uses: taiki-e/install-action@decb84fb327e5b809630c914eb4d1ca67cf59966 # v2.85.14
        with:
          tool: cargo-make
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Cargo check
        run: cargo check --locked --workspace --examples --tests

      - name: Cargo test
        run: cargo test --locked --workspace

      - name: Clippy check
        run: cargo clippy --workspace --all-targets --lib --bins --tests --benches --examples

      - name: "Cargo fmt"
        run: cargo make format-check

      - name: Docs
        env:
          RUSTDOCFLAGS: --cfg docsrs
        run: cargo doc --workspace --all-features --no-deps --document-private-items

  msrv:
    name: Minimal Supported Rust Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: ${{ env.MSRV }}
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - name: Check MSRV
        run: cargo +$MSRV check --workspace --all-targets

  minimal-versions:
    name: Minimal Direct Dependency Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
      - name: Resolve direct deps to minimum versions
        run: cargo +nightly -Z direct-minimal-versions update
      - name: Check lib at minimum versions
        run: cargo check --lib --locked

  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          command: check
          arguments: --workspace --all-features
          command-arguments: "-Dwarnings"
